services:
 db:
   image: postgres:15
   container_name: cloud-app-db
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: appdb
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data

 backend:
   build: ./backend/CloudBackend.Api
   container_name: cloud-app-backend
   ports:
     - "8081:8081"
   depends_on:
     - db

 frontend:
   build: ./frontend
   container_name: cloud-app-frontend
   ports:
     - "8080:8080"
   depends_on:
     - backend

volumes:
 postgres_data:
